// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARyhqymTeagpRYlYkI9hCOAZmD1aOOEV0',
    appId: '1:478058651243:web:1b78b533dffe3e045e5b2e',
    messagingSenderId: '478058651243',
    projectId: 'shop-system-d5d87',
    authDomain: 'shop-system-d5d87.firebaseapp.com',
    storageBucket: 'shop-system-d5d87.firebasestorage.app',
    measurementId: 'G-NLF17DHTQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEEEAcWh6vz2x040cAetQG2eHoMMOgCh0',
    appId: '1:478058651243:android:eec939853477be655e5b2e',
    messagingSenderId: '478058651243',
    projectId: 'shop-system-d5d87',
    storageBucket: 'shop-system-d5d87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf0vUbbePSEV_rjTBAZ-XUznUyV2G3GCk',
    appId: '1:478058651243:ios:1fc72b26072a2fe05e5b2e',
    messagingSenderId: '478058651243',
    projectId: 'shop-system-d5d87',
    storageBucket: 'shop-system-d5d87.firebasestorage.app',
    iosBundleId: 'com.example.dhabayihLmamlaka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf0vUbbePSEV_rjTBAZ-XUznUyV2G3GCk',
    appId: '1:478058651243:ios:1fc72b26072a2fe05e5b2e',
    messagingSenderId: '478058651243',
    projectId: 'shop-system-d5d87',
    storageBucket: 'shop-system-d5d87.firebasestorage.app',
    iosBundleId: 'com.example.dhabayihLmamlaka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARyhqymTeagpRYlYkI9hCOAZmD1aOOEV0',
    appId: '1:478058651243:web:8203244fd07114945e5b2e',
    messagingSenderId: '478058651243',
    projectId: 'shop-system-d5d87',
    authDomain: 'shop-system-d5d87.firebaseapp.com',
    storageBucket: 'shop-system-d5d87.firebasestorage.app',
    measurementId: 'G-DJZZNW4ZN4',
  );
}
